Added Pull Request template,modified application.properties
PSMRI/FHIR-API pull request #21
Opened 2023-10-06 13:00 UTC by swetatech24

2023-10-09 10:28 UTC, drtechie requested changes
Refer to #22

2023-10-10 08:16 UTC, drtechie commented on src/main/resources/application.properties
There are other variables that need to be moved too.
For example eaushadi is pointing to uat. This can't be in application.properties.
FHIR credentials, commonAPI URLs too.

2023-10-10 11:28 UTC, drtechie commented on src/main/environment/common_test.properties
> +start-FHIR-resource-bundle-scheduler=true
See, move the properties that will change per env to common_env.properties.
Rest must be in application.properties. 
Like all these cron properties need not be repeated for every env.

2023-10-19 12:54 UTC, ravishanigarapu approved these changes
looks ok

2023-10-23 06:27 UTC, drtechie approved these changes

2023-10-23 06:27 UTC, merged